fishjam-cloud/mobile-client-sdk

examples/video-chat/hooks/useJoinRoom.ts
examples/video-chat/screens/RoomScreen.tsx
examples/video-chat/scripts/lint.sh
examples/video-chat/scripts/lint_check.sh
examples/webdriverio-test/scripts/lint.sh
examples/webdriverio-test/scripts/lint_check.sh
packages/react-native-client/scripts/lint.sh
packages/react-native-client/scripts/lint_check.sh
packages/react-native-client/src/common/webRTC.ts
packages/react-native-client/src/hooks/useAudioSettings.ts
packages/react-native-client/src/hooks/useCamera.ts
packages/react-native-client/src/hooks/usePeers.ts
packages/react-native-client/src/hooks/useScreencast.ts
packages/react-native-client/src/index.tsx
packages/react-native-client/src/types.ts

Remove `enum`s from TypeScript code. And use `union`s instead. 
Fix bug, where `EncodingReason` had incorrect mapping to native part.
Enums bad. Unions good.

[FCE-274] Remove enums from SDK

---

.github/workflows/all_packages_release.yaml
RELEASE.md

Changes:
Now every tag which regex is type of: [0-9]+.[0-9]+.[0-9]+ will trigger release workflow
removed deprecated step variable
add permission to write, so it can create release on github
Example of working sollution can be found here:
[repo](https://github.com/karkakol/temp)
[npm](https://www.npmjs.com/package/@karolkakol/my-ts-lib)
[cocoapods](https://github.com/CocoaPods/Specs/commit/fed7551db348c1a66477c7ea35e33c26dbebd200)

update release workflow

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/Command.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/CommandsQueue.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientListener.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/models/AuthError.kt
packages/android-client/FishjamClient/src/test/java/com/fishjamcloud/test/client/FishjamClientTest.kt
packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
packages/ios-client/Sources/FishjamClient/FishjamClientListener.swift
packages/ios-client/Sources/MembraneRTC/Types/AuthError.swift
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/Errors.kt
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift

This PR adds error handling of auth errors like invalid/expired token etc. 
The commands queue no longer ends jobs by throwing exceptions but ends them gracefully.
It also makes errors on RN Android nicer (all possible errors with error messages are specified in one file).

[FCE-312] Handle auth errors

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/events/Event.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/webrtc/RTCEngineCommunication.kt
packages/ios-client/Sources/FishjamClient/FishjamClient.swift
packages/ios-client/Sources/MembraneRTC/MembraneRTC.swift
packages/ios-client/Sources/MembraneRTC/RTCEngineCommunication.swift
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/EmitableEvents.kt
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClient.kt
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClientModule.kt
packages/react-native-client/ios/Events.swift
packages/react-native-client/ios/RNFishjamClient.swift
packages/react-native-client/ios/RNFishjamClientModule.swift
packages/react-native-client/src/RNFishjamClientModule.ts
packages/react-native-client/src/common/eventEmitter.ts
packages/react-native-client/src/common/metadata.ts
packages/react-native-client/src/hooks/usePeers.ts

React Native SDK exports functions/types that reference both Peers and Endpoints. From an end user perspective, they are basically the same thing. So, let's rename/remove references to them from public API.

[FCE-212] Rename references from "endpoint" to "peer" in RN-SDK API

---

examples/video-chat/screens/RoomScreen.tsx
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt

To reproduce:
- run room manager
- add some peers with video AND audio tracks
- connect mobile to the room
- some tracks will be black squares
What happened? The old videoroom was sending track metadata which contained "type" value set to "audio" for audio track. The new videoroom doesn't send any metadata. So the example app treated audio tracks like video track.
Fixed by checking the type of the track, not metadata.
I'm not sure if this is the bug that @mironiasty have experienced but after fixing that everything works ok for me - I can see all the video tracks, no black squares and I can turn on/off some of the tracks.

Fix room manager audio tracks

---

packages/react-native-client/src/components/VideoPreviewView.tsx
packages/react-native-client/src/hooks/useCamera.ts
packages/react-native-client/src/types.ts

Branded types are nice tool for restricting type of values that can be passed into functions.
This change converts camera id into such type. This way, when switching camera, developer won't be able to pass arbitrary string. It will be possible to pass only id we are allowing to use.
Add better restriction to API

[FCE-402] Use branded type as camera id

---

examples/video-chat/screens/ConnectWithRoomManagerScreen.tsx

Connection response can contain non-JSON data, e.g. `Bad Gateway`, we now return raw response because of that. The error is now also logged.
This change is made to improve developer experience of using the example application.
Manual testing on the Android emulator.

[FCE-469] Handle non-JSON connection errors and warn

---

examples/video-chat/screens/ConnectWithRoomManagerScreen.tsx

This change provides better heuristics for fixing copy-pasted connection URLs.
There are three places that the user can get the connection URL:
- admin panel main page
- app view
- self-crafted from the app view
URL entry now allows for the app-view-formatted URL, by appending `/room-manager`. We also trim the string as a bonus.
Without this, the user would get a very misleading `Not Found` error from the Fishjam instance.
Manual on both Android and iOS emulator/simulator.

Accept Fishjam's path as Room Manager's

---

examples/fishjam-chat/navigators/AppNavigator.tsx
examples/fishjam-chat/screens/ConnectWithRoomManagerScreen.tsx
examples/fishjam-chat/screens/ConnectWithTokenScreen.tsx
examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
packages/ios-client/Sources/FishjamClient/FishjamClient.swift
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClient.kt
packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClientModule.kt
packages/react-native-client/ios/RNFishjamClient.swift
packages/react-native-client/ios/RNFishjamClientModule.swift
packages/react-native-client/src/RNFishjamClientModule.ts
packages/react-native-client/src/common/client.ts
packages/react-native-client/src/index.tsx

As we already have `leaveRoom` method, lets rename `connect` to `joinRoom` to keep naming parity.
Also rename peerTokne/peerMetadata to participantToken/participantMetadata.
To make API more intuitive
X.X.X)

[FCE-532] Rename `connect` to `joinRoom`

---

packages/react-native-client/ios/RNFishjamClient.swift

- Local video track was not filtered out when camera was disabled, this was caused by wrong type passed from the native side `Metadata` (`AnyJson` under the hood) which is not supported.
- Added return value to `toggleCamera` to make it the same as on Android.
- When camera was disabled, empty preview was still displayed on iOS.
-  Successfully disabled camera on iOS and video preview was hiddem

[FCE-535]: Fix iOS preview when camera disabled

---

packages/react-native-client/plugin/src/types.ts
packages/react-native-client/plugin/src/withFishjamAndroid.ts
packages/react-native-client/plugin/src/withFishjamIos.ts

Allow expo plugin to be used without any params.
When plugin is used with empty configuration, it crashes prebuild step

Add defaults to expo plugin

---

packages/react-native-client/src/common/client.ts
packages/react-native-client/src/common/metadata.ts
packages/react-native-client/src/index.tsx

Make participant metadata optional in joinRoom
There are also few small changes to docs
As we could pass metadata form server SDK now, we can make this param optional. It should not be required.
X.X.X)

Make participant metadata optional in joinRoom

---

examples/fishjam-chat/navigators/AppNavigator.tsx
examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx

Enable back button for preview screen and disable back gesture for room screen in `fishjam-chat`.
If I make a mistake in credentials for joining room I would like to be able to close the screen and fix it. Currently only the back gesture wasn't disabled and could be used to go back.
Additionally, I could use the gesture to go back from the room screen instead of having to tap end call button.

Disable back button and gesture only in room

---

.github/workflows/react_native_e2e_android.yaml

- Bumped to new action version 
- The previous version will be deprecated by 30.11.2024
I didn't test it as this action is disabled right now, however, other actions already use the same syntax so there should be no problems.

[FCE-366] Update deprecated artefact-action in workflows

---

examples/fishjam-chat/app.json
examples/fishjam-chat/package.json
packages/android-client/FishjamClient/build.gradle
packages/react-native-client/android/build.gradle
yarn.lock

- Downgraded `minSdkVersion` to 21
- Upgraded `targetSdk` and `compileSdk` to 34
- Removed `expo-build-properties` from the example because it's not needed anymore
We required our SDKs users to have minSdkVersion of at least 24, which didn't work out of the box for a new expo app. 
- Build and run Android after repo clean

Change minSdkVersion to 21

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClient.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
packages/ios-client/Sources/FishjamClient/FishjamClient.swift
packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift

Participants were not updating when leaving room. We should call `PeersUpdate` event after disconnecting.

[FCE-475] Call PeersUpdate event on leaveRoom

---

examples/fishjam-chat/components/VideosGrid.tsx
examples/fishjam-chat/screens/ConnectWithRoomManagerScreen.tsx
examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
examples/fishjam-chat/types/metadata.ts
packages/ios-client/Sources/FishjamClient/FishjamClient.swift
packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
packages/react-native-client/ios/RNFishjamClient.swift

Updated metadata to match Fishjam and removed `join` method on iOS SDK to match Android while also passing correct peer metadata instead of empty one.

[FCE-578] Update metadata and fix iOS metadata handling

---

packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift

- Synchronized event emitting on Android and iOS
Events could sometimes be emitted from wrong thread (for example when value was changed from a different thread than main). 
- Tested event emitting on Android and iOS

[FCE-670]: Fix events emitted from wrong thread

---

packages/ios-client/Sources/FishjamClient/CommandsQueue.swift
packages/ios-client/Sources/FishjamClient/media/Capturers/CameraCapturer.swift
packages/ios-client/Sources/FishjamClient/media/Dimensions.swift
packages/ios-client/Sources/FishjamClient/ui/VideoView.swift
packages/ios-client/Sources/FishjamClient/utils/String+Error.swift
packages/react-native-client/ios/RNFishjamClient.swift

Remove protocol conformances resulting in `extension declares a conformance of imported type '[...]' to imported protocol '[...]'; this will not behave correctly if the owners of '[...]' introduce this conformance in the future` warnings
We should avoid adding such protocol conformances since it may result in issues in the future. ~~And because because `Dimensions` is only compared once then it seems better to just do the comparison in place.~~
`Dimensions` would work better as a wrapper of `CMVideoDimensions`

[FCE-667] Remove protocol conformances resulting in warnings

---

FishjamCloudClient.podspec
packages/android-client/FishjamClient/build.gradle

- Looks like WebRTC SDK upgrade disabled video preview on iOS
- Video preview doesn't work on iOS
- Run iOS app without SDK upgrade

[FCE-712]: Fix ios preview

---

packages/react-native-client/src/hooks/useAppScreenShare.ts
packages/react-native-client/src/hooks/useScreenShare.ts
packages/react-native-client/src/types.ts

- `peerMatadata` was different between mobile and web.
- Screen sharing was not displayed in video room
X.X.X)

FCE-724: Fix mobile screensharing doesn't work with video room

---

examples/fishjam-chat/package.json
yarn.lock

- Bumped gorhom/bottom-sheet
- Reanimated was giving a warning. Newer version of bottom-sheet has this issue fixed. 
- Run on iOS/Android

[FCE-800]: Fix Reanimated Warning

---

examples/fishjam-chat/components/VideosGrid.tsx
packages/ios-client/Sources/FishjamClient/webrtc/PeerConnectionManager.swift
packages/react-native-client/src/common/webRTC.ts
packages/react-native-client/src/components/VideoRendererView.tsx
packages/react-native-client/src/hooks/usePeers.ts
packages/react-native-client/src/index.tsx

Instead of strings, our IDs can be defined as branded types. This way it won't be possible* to use Track ID instead of Peer ID in typescript code
*ok, it would be possible if someone does not care about proper TS
This change should make our API less error prone
App is still passing CI checks

[FCE-804] Add branded IDs for peers and tracks

---

packages/react-native-client/src/hooks/useMicrophone.ts

Refactored `useMicrophone` code to use `useFishjamEventState` instead of `useState` and `useFishjamEvent`.
The code will be simpler and less error-prone. It should fix FCE-809 as well.

[FCE-821] Make useMicrophone stateless

---

packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
packages/react-native-client/ios/RNFishjamClient.swift
packages/react-native-client/ios/RNFishjamClientModule.swift
packages/react-native-client/src/RNFishjamClientModule.ts
packages/react-native-client/src/hooks/useFishjamEventState.ts
packages/react-native-client/src/hooks/usePeers.ts

Refactored `usePeers` code to use `useFishjamEventState` instead of `useState` and `useFishjamEvent`.
The code will be simpler and less error-prone.

[FCE-830] Make usePeers stateless

---

packages/react-native-client/src/hooks/useAppScreenShare.ts
packages/react-native-client/src/hooks/useBandwidthEstimation.ts
packages/react-native-client/src/hooks/usePeerStatus.ts
packages/react-native-client/src/hooks/useScreenShare.ts

Refactored `useAppScreenShare`, `useScreenShare`, `usePeerStatus`, `useBandwithEstimation` code to use `useFishjamEventState` instead of `useState` and `useFishjamEvent`.
The code will be simpler and less error-prone.

[FCE-846] Make additional hooks stateless

---

packages/react-native-client/src/hooks/useAudioSettings.ts

Refactored `useAudioSettings` code to use `useFishjamEventState` instead of `useState` and `useFishjamEvent`.
The code will be simpler and less error-prone.

[FCE-852] Make useAudioSettings stateless

---

packages/react-native-client/src/common/client.ts
packages/react-native-client/src/common/metadata.ts
packages/react-native-client/src/hooks/usePeerStatus.ts
packages/react-native-client/src/hooks/useReconnection.ts
packages/react-native-client/src/hooks/useUpdatePeerMetadata.ts
packages/react-native-client/src/index.tsx

Instead of static method, let's have hook that will allow updating metadata.
I also updated jsdoc comments - to remove deprecated methods from existing categories (so they are not easily discoverable in documentation)
Let's have unified API that rely mostly on hooks

[FCE-929] Add useUpdatePeerMetadata hook

---

examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
packages/react-native-client/src/hooks/internal/useFishjamEvent.ts
packages/react-native-client/src/hooks/internal/useFishjamEventState.ts
packages/react-native-client/src/hooks/useAppScreenShare.ts
packages/react-native-client/src/hooks/useAudioSettings.ts
packages/react-native-client/src/hooks/useBandwidthEstimation.ts
packages/react-native-client/src/hooks/useCamera.ts
packages/react-native-client/src/hooks/useConnection.ts
packages/react-native-client/src/hooks/useMicrophone.ts
packages/react-native-client/src/hooks/usePeerStatus.ts
packages/react-native-client/src/hooks/usePeers.ts
packages/react-native-client/src/hooks/useReconnection.ts
packages/react-native-client/src/hooks/useScreenShare.ts
packages/react-native-client/src/index.tsx

This is change in `joinRoom` API where it will be unified with web API - param will be object.
Here is related change in web SDK: https://github.com/fishjam-cloud/web-client-sdk/pull/206
Here is related change in documentation: https://github.com/fishjam-cloud/documentation/pull/62
We should aim for similar API on all platforms, and this is yet another step to unify it (this time Web part had better approach)
This is 'just' a change in method typing.

[FCE-931] Unify joinRoom signature with web

---

examples/fishjam-chat/app.json
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/EmitableEvents.kt
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
packages/react-native-client/ios/Events.swift
packages/react-native-client/ios/RNFishjamClient.swift
packages/react-native-client/ios/RNFishjamClientModule.swift
packages/react-native-client/src/RNFishjamClientModule.ts
packages/react-native-client/src/hooks/useCamera.ts

- Removed warning when `prepareCamera` was called multiple times
- Added a property that indicates if the amera was already initialized
- It was misleading for SDK users what this warning meant. 
- Tested on iOS and Android.

FCE-1023: Change how prepareCamera works

---

packages/ios-client/Sources/FishjamClient/webrtc/helpers/TrackBitratesMapper.swift
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift

- Sends trackIdToBitrates on iOS (temporarily)
- Fixed audio metadata
- Fishjam requires trackId to bitrate mapping (even though it should not be required). This fix temporarily enables it on iOS.
- Fixed microphone on iOS, Android and Web

FCE-1042: Fix microphone track

---

examples/fishjam-chat/package.json
package.json
packages/react-native-client/package.json

Release 0.7.0

---

.github/workflows/all_packages_lint.yaml
packages/react-native-client/src/hooks/useAppScreenShare.ts
packages/react-native-client/src/hooks/useCamera.ts
packages/react-native-client/src/index.tsx
packages/react-native-client/src/types.ts
typedoc.json

Export all types that are visible to end user, but were not yet exported
Fix typedoc syntax marked as incorrect
Update typedoc configuration to only generate docs for React Native package
I also updated workflow config - to add emojis (as on web) and new step that generate docs.
I want to update our documentation, but as part of this process I want to remove warnings (and also add missing types into docs)
Run all CI checks

[FCE-1039] Update types exports (and typedoc) to make `yarn docs` happy

---

packages/react-native-client/android/build.gradle

Current path might not work with all environments that package can be used.
So it is updated (to match iOS).
Building app for android might not be possible without this patch.
`mobile-client-test-app` has been used to verify this change (also Android version of `fishjam-chat` was build locally to confirm that fix works well with monorepo)

[FCE-1123] Update path to package.json in build.gradle

---

.github/actions/setup/action.yml
.github/workflows/docs.yaml

Update all actions related to publishing docs for this project
As of today, [actions/upload-artifact](https://github.com/actions/upload-artifact) is no longer available. So we have to update all actions that depend on it.
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
It will be tested by merging and checking if action will run correctly (it is not 'mission critical', so it can fail)

[FCE-1126] Update publish docs action

---

packages/react-native-client/ios/VideoPreviewView.swift
packages/react-native-client/ios/VideoRendererView.swift

- Assign frame to subview when layoutSubviews is called
Fabric probably caused this, however, I cannot locate the exact cause, so this is more of a solution to a cause rather than a proper fix. 
Run preview and render screen on iOS.

[FCE-1115] - Preview doesn't work on SDK 52

---

packages/react-native-client/plugin/src/withFishjamAndroid.ts

- Fixed the script to close foregorund service on app close
- There was a bug which allowed for stream to still be running after the app was closed.
- This can be further improved by using Headless JS but this requires another task. 
- Reproduced the bug and then checked if it's not streaming anymore after the app is closed.

[FCE-1147] - Android can still stream even if app is killed

---

packages/react-native-client/src/utils/eventPayloadValidator.ts

- Disabled metadata validation for tracks
- Tracks are user specific so no point in validating them on our side.
- Tested if error is not present when connected with the video room. 

[FCE-1141]: When connecting between web and mobile SDK, there validation error on mobile

---

packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
packages/react-native-client/ios/RNFishjamClient.swift

- Added a lock when calling startCamera to prevent race conditions. 
- Also added a lock for iOS
- If start camera was called too soon, it resulted in an undefined state. 
- Tested calling prepareCamera multiple times on Android.

FCE-1142: Calling prepareCamera twice on Android breaks preview

---

packages/react-native-client/ios/VideoPreviewView.swift
packages/react-native-client/ios/VideoRendererView.swift

- Fixed frame assigned instead of bounds
Stupid error. The frame also contains parent coordinates and we only need to assign the size...
- Tested the case on iOS

FCE-1153: Fix frame to bounds

---

packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewView.kt

- Removed view disposing on Android when detached from window.
- I'm not sure what was the reason for this, but once the view is released it would have to be recreated to work again. There is also code in ViewModule that calls this when the view gets destroyed so there shouldn't be any leaks. 
- Tested if view reinitializes when returning from a different tab.

FCE-1155: Fix Android view not reattached

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientListener.kt
packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
packages/ios-client/Sources/FishjamClient/FishjamClientListener.swift
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift

- Added a warning when an inactive track is present in an SDP answer. This usually means it was impossible to negotiate the track because of incompatible codecs. 
- We want to inform users why video is not working.
- Only tested on Android Emulator as iOS supports all available codecs in Fishjam.

FCE-1179: Handle unsupported codecs in sdpAnswer

---

packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoRendererView.kt
packages/react-native-client/ios/VideoRendererView.swift

- Fixed local camera track not stopped
- Fixed a bug that listener was never removed
- The bug was introduced here: https://github.com/fishjam-cloud/mobile-client-sdk/pull/330 
I missed the fact that it also handled disposing of the current capturer, therefor it had always camera on.
- Tested od Android and iOS

FCE-1229: Fix camera track not stopped

---

.github/workflows/publish-react-native.yml
.github/workflows/release.yml

- Created a reusable workflow so that if something fails we can still release RN package manually. 
- Sometimes iOS or Android releases fail but the spec is published. This makes it impossible to release RN so we need a way to do it manually. 
- Not possible before merge

FCE-1255: Add ability to trigger RN relase manually

---

.github/actions/publish-react-native-client/action.yml
.github/workflows/publish-react-native.yml
.github/workflows/release.yml

- Transformed release rn to action
- npm token is now required and correctly passed from workflows
- the workflow was failing when called from a different workflow because of missing npm token
- not possible to test until next release

FCE-1328: Fix release action envs

---

examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx

- Added aspect ratio to preview
- Preview was stretched and looked weird.  This is a temp fix as this issue should also resolve when https://linear.app/swmansion/issue/FCE-1181 is done.
- Tested on android

FCE-1312: Fix Android preview stretched

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/models/Endpoint.kt
packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/models/RoomState.kt
packages/android-client/FishjamClient/src/main/java/fishjam/PeerNotifications.java
packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
packages/ios-client/Sources/FishjamClient/models/Endpoint.swift
packages/ios-client/Sources/FishjamClient/models/RoomState.swift
packages/ios-client/Sources/FishjamClient/models/TrackTypeError.swift
packages/ios-client/Sources/FishjamClient/protos/fishjam/peer_notifications.pb.swift
packages/react-native-client/ios/RNFishjamClient.swift

- Blocked ability to join room with video tracks added
- Updated protos
- This change was required to prevent errors when trying to add video tracks to audio only rooms
Run and tested on iOS and Android

FCE-1305: Prevent adding of video tracks to audio-only rooms on mobile

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/ui/VideoScalingCalculator.kt

- Fix aspect ratio calculations. The issue was caused by floats comparison.
- When using a custom aspect ratio the view was incorrectly calculated if aspect ratios where the same.
- Tested on Android

FCE-1411: Fix aspect ratio on Android Example

---

examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewView.kt
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoRendererView.kt
packages/react-native-client/ios/VideoPreviewView.swift

I could not completely remove it due to the need for a native callback when the view is hidden; however, I did a refactor that makes Preview inherit from `VideoRendererView`. That solves the issue of duplicated code (aka hidden errors). 
- More code sharing, and easier maintenance. 
- Run and tested Android + iOS

FCE-1181: Remove native VideoPreviewView

---

packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt

- If there are no tracks, don't renegotiate / add track. 
- When joining a room with no tracks, fishjam was closing the connection. The flow was like that CONNECTED => RENEGOTIATE TRACKS => SDP OFFER. We cannot send sdp offer unless we have tracks to share. This was already properly handled on iOS.
- Tested no tracks room on Android/iOS

FCE-1420: Audio only randomly crashing on android

---

internal/fishjam-chat/screens/LivestreamScreen/LivestreamStreamerScreen.tsx
packages/react-native-client/src/components/LivestreamStreamer.tsx
packages/react-native-client/src/hooks/useLivestreamStreamer.ts
packages/react-native-client/src/index.tsx

- Changed API a bit to make it bound to the LivestreamView. Right now it's obvious that you need to use `useLivestreamStreamer` hook (because of the passed reference). It also helps with initializing the view, it's closer to the native cycle rather than the hook.
The current API was not ideal. 
Android + iOS 

FCE-1867: Livestreaming improvements

---

.github/workflows/expo_doctor.yaml
packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
packages/react-native-client/ios/RNFishjamClient.swift
packages/react-native-client/package.json
yarn.lock

- Emit a warning and return when `joinRoom` is called after already connected/connecting.
- Bumped rn-whip-whep (broken release was causing iOS build to fail)
- Calling `joinRoom` multiple times was causing an undefined state, which was difficult to debug. 
iOS + Android

FCE-1882: Fix multiple calls to joinRoom

---

internal/fishjam-chat/screens/ConnectWithFishjamRoom.tsx
packages/react-native-client/src/components/FishjamRoom/index.tsx

Change the implementation of FishjamRoom so that it uses fishamId instead of url to connect to the room.
We update the FishjamRoom component so that it uses the new way of joining the fishjam room.
I've tested this in the fishjam-chat app

Make FishjamRoom use id instead of url to join room
