fishjam-cloud/mobile-client-sdk

- examples/webdriverio-test/.env.example
- packages/react-native-client/android/build.gradle
- packages/react-native-client/android/src/main/java/org/membraneframework/reactnative/RNFishjamClient.kt
> Merge android-client-sdk up to date

- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/hooks/useCamera.ts
Update code to make sure that passed config is readonly
Prevent possible bugs
> [FCE-276] Fix potential issue with useCamera, where config is modified as side effect

- examples/video-chat/hooks/useJoinRoom.ts
- examples/video-chat/screens/PreviewScreen/index.tsx
- examples/video-chat/screens/RoomScreen.tsx
- packages/react-native-client/src/common/client.ts
- packages/react-native-client/src/hooks/useCamera.ts
- packages/react-native-client/src/hooks/useMicrophone.ts
- packages/react-native-client/src/hooks/usePeers.ts
- packages/react-native-client/src/stats/useRTCStatistics.ts
Various small changes in code, that were not added in my previous commits.
- always use `await` instead of `then`
- type improvements
- `usePeer` should return object instead of direct value
> [NO-TICKET] Small fixes in SDK code

- examples/video-chat/screens/ConnectWithTokenScreen.tsx
- packages/ios-client/Sources/MembraneRTC/Media/Capturers/CameraCapturer.swift
- packages/ios-client/Sources/MembraneRTC/Media/Tracks/LocalVideoTrack.swift
- packages/ios-client/Sources/MembraneRTC/UI/VideoView.swift
Make front camera properly mirrored. Previously front camera preview was mirrored compared to e.g. aparat app. Also add some animation during camera change.
> [FCE-29] Karkakol/ios fix camera flip

- examples/video-chat/components/Button.tsx
- examples/video-chat/components/DismissKeyboard.tsx
- examples/video-chat/components/InCallButton.tsx
- examples/video-chat/components/LetterButton.tsx
- examples/video-chat/components/NoCameraView.tsx
- examples/video-chat/components/QRCodeScanner.tsx
- examples/video-chat/components/SoundOutputDevicesBottomSheet.tsx
- examples/video-chat/components/SoundOutputDevicesSection.tsx
- examples/video-chat/components/TextInput.tsx
- examples/video-chat/components/Typo.tsx
- examples/video-chat/components/VideosGrid.tsx
- examples/video-chat/components/index.tsx
- examples/video-chat/screens/ConnectWithRoomManagerScreen.tsx
- examples/video-chat/screens/PreviewScreen/index.tsx
- examples/video-chat/screens/RoomScreen.tsx
- yarn.lock
There are few changes in this PR:
- update bottom sheet dependency, as latest version fix reanimated warning
- Order all example components in same way (imports/types/helper functions/main component/styles)
- Remove inline functions from example components
- unify export strategy for these components
To make code better, as this is our example app.
Typescript check was run, and app was tested
> [FCE-338] Small code refactor for example app

- .github/workflows/static.yaml
- .gitignore
- package.json
- packages/react-native-client/typedoc.json
- typedoc.json
- yarn.lock
Add basic documentation to project. Before we will add beautiful docs 
Let just have some basic docs for now
> [FCE-352] Add typedoc + GH actions

- .github/workflows/docs.yaml
- package.json
- typedoc.json
- yarn.lock
Sync documentation styling with `web-client-sdk` and `js-server-sdk`
Unify project configuration
> [NO-TICKET] Add simple styling for docs

- README.md
- examples/video-chat/screens/ConnectWithRoomManagerScreen.tsx
- examples/webdriverio-test/utils.ts
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClient.kt
- packages/android-client/FishjamClient/src/test/java/com/fishjamcloud/test/client/FishjamClientTest.kt
- packages/ios-client/Sources/FishjamClient/FishjamClient.swift
- packages/ios-client/Tests/FishjamClientTests/FishjamClientTests.swift
Add URL suffix manually, as Room Manager will no longer return in
This is related to this change: https://github.com/fishjam-cloud/js-server-sdk/pull/25
To make example app work with latest Room Manager
> [FCE-378] Fix Room Manager support

- examples/video-chat/components/TextInput.tsx
- examples/video-chat/components/VideosGrid.tsx
- examples/video-chat/screens/ConnectWithRoomManagerScreen.tsx
- examples/video-chat/screens/ConnectWithTokenScreen.tsx
- examples/video-chat/screens/PreviewScreen/PreviewScreen.tsx
- examples/video-chat/screens/RoomScreen.tsx
This PR simplifies how camera grid works in mobile app. 
- removing animations (they were breaking styling, and we don't really need them in demo app now
- show user names in each video tile
- do not change video aspect ratio
- set correct user name when connection starts
This changes are mostly to make debugging and working on future features a little easier.
Manual testing
> [FCE-400] Improve camera grid view

- examples/video-chat/components/VideosGrid.tsx
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/hooks/usePeers.ts
- packages/react-native-client/src/types.ts
Remove metadata from tracks returned from SDK
These values should be opaque to user.
> [FCE-390] Remove metadata from track info

- examples/fishjam-chat/ios/FishjamExample.xcodeproj/project.pbxproj
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
- packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
Add call renegotiation after connect
> [FCE-501] add renegotiate after connect

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- Fixed param name
- Android build fails after rename
- Build android
> Fix android build

- packages/react-native-client/ios/RNFishjamClientModule.swift
- Fixed Swift function placeholder
- After refactor we probably overlooked the change
- Build iOS
> Fix iOS build

- packages/react-native-client/README.md
Describe your changes in detail
X.X.X)
> Update readme images paths

- FishjamCloudClient.podspec
- package.json
- packages/react-native-client/android/build.gradle
- packages/react-native-client/ios/RNFishjamClient.podspec
- packages/react-native-client/package.json
Release 0.2.3 
This release will fix small issues related to expo plugin and versioning.
> Release 0.2.3

- FishjamCloudClient.podspec
- package.json
- packages/react-native-client/android/build.gradle
- packages/react-native-client/ios/RNFishjamClient.podspec
- packages/react-native-client/package.json
> Relese 0.2.4

- CONTRIBUTING.md
- README.md
- examples/fishjam-chat/README.md
- packages/react-native-client/plugin/src/withFishjamIos.ts
- Fixed an if statement causing the iOS build to fail after subsequent `expo prebuild`s. 
- Build was failing after calling `expo prebuild` more than one time. 
- Build and run iOS + Android
> [FCE-540]: Make expo plugin overridable

- README.md
- RELEASE.md
- packages/react-native-client/README.md
Update main readme file. Also make some changes in release documentation.
> [FCE-572] Cleanup main readme

- examples/fishjam-chat/components/VideosGrid.tsx
- examples/fishjam-chat/navigators/AppNavigator.tsx
- examples/fishjam-chat/screens/ConnectWithRoomManagerScreen.tsx
- examples/fishjam-chat/screens/ConnectWithTokenScreen.tsx
- examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
- examples/fishjam-chat/screens/RoomScreen.tsx
- examples/fishjam-chat/types/metadata.ts
- examples/webdriverio-test/test/specs/test.e2e.ts
- packages/ios-client/README.md
- packages/ios-client/Sources/FishjamClient/FishjamClient.swift
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/ios/RNFishjamClientModule.swift
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/common/client.ts
- packages/react-native-client/src/common/metadata.ts
- packages/react-native-client/src/components/VideoRendererView.tsx
- packages/react-native-client/src/hooks/usePeers.ts
- packages/react-native-client/src/index.tsx
- Renamed all occurrences of `participant` to `peer`.
- Rename was requested at a meeting
- Built and connected to a room containing participants both on Android and iOS
- [] My code follows the code style of this project.
> [FCE-582]: Rename Participant back to Peer on mobile

- README.md
- packages/android-client/README.md
- packages/ios-client/README.md
- packages/react-native-client/LICENSE
- packages/react-native-client/README.md
Add info about Software Mansion to our README files
Let's improve SWM visibility by adding SWM info
> [FCE-592] Add info about Software Mansion into README files

- FishjamCloudClient.podspec
- package.json
- packages/react-native-client/android/build.gradle
- packages/react-native-client/ios/RNFishjamClient.podspec
- packages/react-native-client/package.json
Release new version of library
There were few important changes in library, so let's release new version
> Release 0.3.0

- examples/webdriverio-test/utils.ts
- packages/ios-client/package.json
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewView.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewViewModule.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoRendererView.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoRendererViewModule.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoView.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/managers/LocalCameraTracksChangedListenersManager.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/managers/LocalTracksSwitchListenersManager.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/managers/TracksUpdateListenersManager.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/ios/Utils/PermissionUtils.swift
- packages/react-native-client/ios/VideoPreviewView.swift
- packages/react-native-client/ios/VideoRendererView.swift
- packages/react-native-client/ios/managers/LocalCameraTracksChangedListenersManager.swift
- packages/react-native-client/ios/managers/TracksUpdateListenersManager.swift
- packages/react-native-client/scripts/lint.sh
- packages/react-native-client/scripts/lint_check.sh
> [FCE-603] Karkakol/add observer pattern

- CONTRIBUTING.md
- README.md
- examples/fishjam-chat/README.md
- packages/react-native-client/README.md
Various updates in README files, to make them up to date with recent changes
W should have updated documentation
X.X.X)
> Update README files across repo

- packages/react-native-client/android/build.gradle
I couldn't reproduce the bug on any device so this is just an upgrade of audioswitch library. 
- Run and tested on Android if still works with a newer version
> FCE-44: Bump audioswitch version

- FishjamCloudClient.podspec
- packages/android-client/FishjamClient/build.gradle
- Upgraded WebRTC-SDK version
- Version was a little outdated
- Run e2e tests on Android and iOS
> [FCE-683]: Update WebRTC-SDK version

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/ios/RNFishjamClient.swift
I'm not sure if this is the best way to handle it, but it's done similarly on the web 🤷‍♂️ 
Local peer metadata structure was different than on remote.
- Printed peer metadata on Android and iOS
> [FCE-681] Make sure metadata have the same structure between platforms

- TESTING_MANUAL.md
- Added a manual on how to test audio on mobile
- We need a manual testing guide to test audio before release.
- Checked the instruction if steps work. 
> [FCE-623] Investigate how to test audio track on mobile SDK

- examples/fishjam-chat/components/VADIcon.tsx
- examples/fishjam-chat/components/VideosGrid.tsx
- examples/fishjam-chat/screens/RoomScreen/RoomScreen.tsx
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
- packages/ios-client/Sources/FishjamClient/FishjamClientInternal.swift
- packages/react-native-client/src/index.tsx
Fix vad and utilize it in fishjam-chat. VAD status is taken from fishjam, but i discovered it is possible to implement it on native side by working with RTCAudioTrack. Currently when single VAD status changes all endpoints are emitted. This solution might be expensive but it is very simple and it works. In future it might be a good idea to just emit single changed track.
VAD is cool
> [FCE-30] fix vad

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- Fixed peer metadata structure
- 
- Metadata was sent in wrong format
- Run Android/iOS and tested metadata display in videoroom.
> [FCE-726]: Mobile device is visible as Unknown in VideoRoom

- examples/fishjam-chat/components/VideosGrid.tsx
- examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/common/client.ts
- packages/react-native-client/src/hooks/usePeers.ts
- Updated types to reflect real structure of metadata
- It was not obvious how the metadata is passed.
> [FCE-766]: Expose server metadata

- examples/fishjam-chat/navigators/AppNavigator.tsx
- examples/fishjam-chat/screens/ConnectWithFishjamRoom.tsx
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/components/FishjamRoom/GridTrackItem.tsx
- packages/react-native-client/src/components/FishjamRoom/VideosGrid.tsx
- packages/react-native-client/src/components/FishjamRoom/index.tsx
- packages/react-native-client/src/components/FishjamRoom/parsePeersToTracks.ts
- packages/react-native-client/src/hooks/useCamera.ts
- packages/react-native-client/src/index.tsx
- Created the `FishjamRoom` component which should serve as a simple drop-in component for testing
- Created test tab for testing the above component.
- Refactored `startCamera` to return a boolean if the camera was started successfully. 
A simple component was needed for a quicker user onboarding. 
- Build, run and tested on iOS/Android. 
> FCE-684: Simple component

- .eslintrc.js
- examples/fishjam-chat/plugin/src/with-custom-config-android.ts
- examples/fishjam-chat/plugin/src/with-custom-config-ios.ts
- examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
- examples/fishjam-chat/screens/RoomScreen/RoomScreen.tsx
- examples/webdriverio-test/configuration.ts
- packages/react-native-client/plugin/src/withFishjamAndroid.ts
- packages/react-native-client/plugin/src/withFishjamIos.ts
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/debug/stats/useRTCStatistics.ts
- packages/react-native-client/src/hooks/useCamera.ts
- packages/react-native-client/src/hooks/usePeers.ts
This PR updates eslint configuration, to enable `no-shadow` and `no-any` rules. 
Also fixes code in all places where it was required.
`no-shadow` rule helps to keep code more readable - as it is easier to find where some variable was defined.
All lint rules are passing.
> [FCE-827] Enable no-shadow and no-any rules in eslint

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- Fixed type of event emitted on socket close
An error was emitted when the socket was closed, which is not an expected behavior. 
- Run and tested on Android/iOS
> Fix event emitted on socket close

- examples/webdriverio-test/test/specs/test.e2e.ts
- Added more timeout to reduce test flakiness. 
- Tests are flaky. 
- Run locally and on Github multiple times to see if it will error.
> FCE-771: Make mobile e2e tests less Flaczki

- .github/workflows/react_native_e2e_android.yaml
- examples/fishjam-chat/plugin/src/with-custom-config-android.ts
- Added gradle build cache
- This should speed up building e2e tests by ~2-3 minutes
> FCE-868: Improve e2e tests speed

- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/ReconnectionManager.kt
- packages/ios-client/Sources/FishjamClient/ReconnectionManager.swift
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/EmitableEvents.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
- packages/react-native-client/ios/Events.swift
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/ios/RNFishjamClientModule.swift
- packages/react-native-client/src/RNFishjamClientModule.ts
- packages/react-native-client/src/hooks/useFishjamEvent.ts
- packages/react-native-client/src/hooks/useReconnection.ts
Moved useReconnection status logic to native side.
The code will be simpler and less error-prone.
> [FCE-853] Refactor useReconnection to be stateless

- FishjamCloudClient.podspec
- packages/android-client/FishjamClient/build.gradle
Update WebRTC-SDK to 125.6422.06
> [FCE-896] Update WebRTC-SDK to 125.6422.06

- examples/fishjam-chat/hooks/useReconnectionToasts.ts
- packages/react-native-client/src/hooks/useConnection.ts
Separated peer status and connection status.
Combined they cause some issues.
> [FCE-945] Separate peer and connection statuses

- FishjamCloudClient.podspec
- package.json
- packages/react-native-client/android/build.gradle
- packages/react-native-client/ios/RNFishjamClient.podspec
- packages/react-native-client/package.json
> Release `0.6.0`

- examples/fishjam-chat/package.json
- yarn.lock
> Update Expo to 52.0.14

- examples/fishjam-chat/package.json
- yarn.lock
> Update Expo to 52.0.17

- .github/workflows/expo_doctor.yaml
Added GitHub workflow which runs Expo doctor check on pull requests.
We want to see if PR breaks Expo doctor checks in order to keep the best possible compatibility with Expo.
> [FCE-959] Add Expo doctor CI check

- README.md
- examples/fishjam-chat/README.md
- packages/android-client/README.md
- packages/ios-client/README.md
- packages/react-native-client/README.md
- packages/react-native-client/package.json
- typedoc.json
Changed all occurrences of `Fishjam Cloud` to `Fishjam` in user-facing content.
Did not touch codebase
We have settled on Fishjam as the project name.
> Rename Fishjam Cloud to Fishjam FCE-893

- FishjamCloudClient.podspec
- packages/ios-client/FishjamClient.xcworkspace/xcshareddata/swiftpm/Package.resolved
- packages/ios-client/Package.resolved
- packages/ios-client/Package.swift
- packages/react-native-client/package.json
- yarn.lock
- Removed phoenix library from the project
- Phoenix was unused
- Connected to a room successfully 
> FCE-1044: Remove unused phoenix library

- examples/fishjam-chat/screens/PreviewScreen/PreviewScreen.tsx
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/src/components/FishjamRoom/index.tsx
- Added a timeout if promise is not resolved in 15 seconds
- Sometimes an unknown error can occur and promise will never be resolved which may leave the user in an unknown state.
Run example apps on Android and iOS
> [FCE-1113]: Investigate join_room hangs

- package.json
- packages/react-native-client/package.json
> Release 0.8.0

- .github/workflows/release.yml
- Update release workflow to wait for native deps
- Fix android check
- NPM should wait for native deps.
It wasn't 
> Update release worflow

- package.json
- packages/react-native-client/package.json
> Release 0.8.1

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewView.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoPreviewViewModule.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/VideoRendererView.kt
- packages/react-native-client/expo-module.config.json
- packages/react-native-client/ios/VideoPreviewView.swift
- packages/react-native-client/ios/VideoPreviewViewModule.swift
- packages/react-native-client/ios/VideoRendererView.swift
- packages/react-native-client/src/components/VideoPreviewView.tsx
- Reverted VideoPreviewView to its original state
- This tasks needs a different approach
- Run and tested on Android and iOS
> Revert "FCE-1181: Remove native VideoPreviewView (#330)"

- package.json
- packages/react-native-client/package.json
> Release 0.13.0

- packages/android-client/FishjamClient/src/main/java/fishjam/PeerMessageKt.kt
- packages/android-client/FishjamClient/src/main/java/fishjam/PeerNotifications.java
- packages/android-client/FishjamClient/src/main/java/fishjam/ServerMessageKt.kt
- packages/android-client/FishjamClient/src/main/java/fishjam/ServerNotifications.java
- packages/ios-client/Sources/FishjamClient/protos/fishjam/peer_notifications.pb.swift
> Bump protos

- package.json
- packages/react-native-client/package.json
Release new version to support custom sources
> Release 0.14.1

- examples/audio-only/components/RoomInfo.tsx
- Restore enable/disable microphone
- Forgot to apply a stash
Android + iOS
> FCE-1388: Restore use microphone

- packages/android-client/FishjamClient/build.gradle
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClient.kt
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/FishjamClientInternal.kt
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/media/LocalVideoTrack.kt
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/models/CustomSource.kt
- packages/android-client/FishjamClient/src/main/java/com/fishjamcloud/client/webrtc/PeerConnectionFactoryWrapper.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- Created CustomSource for Android
This PR will allow us to implement custom sources (like react-native-vision-camera) for both Android and iOS.
- Not tested yet as there is no example, tested only with sample code on Android.
> FCE-1389: Create CustomSource for Android

- package.json
- packages/react-native-client/package.json
Bump version in package.json
New release
X.X.X)
> Release 0.16.0

- package.json
- packages/react-native-client/package.json
> Release 0.17.0

- .gitignore
- examples/fishjam-chat/navigators/AppNavigator.tsx
- examples/fishjam-chat/screens/ConnectToLivestreamScreen.tsx
- examples/fishjam-chat/screens/LivestreamScreen/LivestreamScreen.tsx
- packages/react-native-client/package.json
- packages/react-native-client/src/components/LivestreamView.tsx
- packages/react-native-client/src/hooks/useLivestream.ts
- packages/react-native-client/src/index.tsx
- yarn.lock
- Integrated WHEP client into our SDK
- We want to support a simple livestreaming interface for our users
Run and tested on Android and iOS
> FCE-1471: Integrate react-native-whip-whep into react-native SDK

- package.json
- packages/react-native-client/package.json
> Release 0.18.0

- examples/audio-only/README.md
- examples/audio-only/package.json
- examples/vision-camera/README.md
- examples/vision-camera/package.json
- Added missing READMEs
- VisionCamera and audio-only examples were missing a readme.
> FCE-1514: Add README to vision-camera example

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
Describe your changes in detail
X.X.X)
> feat: android permissions

- examples/fishjam-chat/README.md
- Implemented additional exaplanation to the example based on Dawid's feedback.
> FCE-1621: Add docs improvements from Dawid

- package.json
- yarn.lock
Describe your changes in detail
X.X.X)
> fix: resolution

- internal/fishjam-chat/app.json
Turns out we need this config anyway...
> Fix EAS Build

- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClient.kt
- packages/react-native-client/android/src/main/java/io/fishjam/reactnative/RNFishjamClientModule.kt
- packages/react-native-client/ios/RNFishjamClient.swift
- packages/react-native-client/ios/RNFishjamClientModule.swift
- packages/react-native-client/src/hooks/useMicrophone.ts
- Added ability to start/stop the microphone 
- Small refactor to incorporate the change
- A client submitted a valid use case where this might be useful. 
- Run and tested iOS + Android 
> FCE-1743: Add startMicrophone / stopMicrophone

- package.json
- packages/react-native-client/package.json
> Bump version to 0.19.1

- package.json
- packages/react-native-client/package.json
Describe your changes in detail
X.X.X)
> Release 0.20.0

- .github/pull_request_template.md
Adds `Documentation impact` section to the PR template
> Update PR template to include doc updates

- package.json
- packages/react-native-client/package.json
> Release 0.22.0
